# -*- coding: utf-8 -*-
"""Lecture9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1seTKqR0A-oBVTzn3LdOw_xx-fZPf-3Wr
"""

# ví dụ minh hoạ 1
import numpy as np
import pandas as pd
from scipy.stats import t
from scipy.stats import f
df = pd.read_csv("/content/drive/My Drive/Dataset/dataVD1_lecture9.csv")
x = df.values[0:42,0]
y = df.values[:,1]
n = len(x)
m = len(y)
xbar =np.mean(x)
print(xbar)
ybar =np.mean(y)
print(ybar)
s12 = np.var(x)
print(s12)
s22 = np.var(y)
print(s22)
Fobs = s12/s22
print(Fobs)
p1 = f.cdf(Fobs,n-1,m-1)+1-f.cdf(1/Fobs,n-1,m-1)
print(p1)
tobs =(xbar - ybar)/np.sqrt(s12/n+s22/m)
print(tobs)
nu = round((s12/n+s22/m)**2/((s12/n)**2/(n-1)+(s22/m)**2/(m-1)))
print(nu)
p2 =2*(1-t.cdf(np.abs(tobs),nu))
print(p2)

# ví dụ minh hoạ 2
from scipy.stats import mannwhitneyu
x=[35, 38, 40, 42, 41, 36]
y=[29, 27, 30, 33, 39, 37]
# compare samples
stat, p = mannwhitneyu(x, y)
print('Statistics=%.3f, p=%.3f' % (stat, p))
# interpret
alpha = 0.05
if p > alpha:
	print('Same distribution (fail to reject H0)')
else:
	print('Different distribution (reject H0)')

# ví dụ minh hoạ 3
import numpy as np
import pandas as pd
from scipy.stats import t
df = pd.read_csv("/content/drive/My Drive/Dataset/dataVD3_lecture9.csv")
x = df.values[:,1]
y = df.values[:,2]
n = len(x)
print(n)
xbar =np.mean(x)
print(xbar)
ybar =np.mean(y)
print(ybar)
xybar =np.mean(x*y)
print(xybar)
x2bar =np.mean(pow(x,2))
print(x2bar)
y2bar =np.mean(pow(y,2))
print(y2bar)
r =(xybar - xbar*ybar)/np.sqrt((x2bar - pow(xbar,2))*(y2bar - pow(ybar,2)))
print(r)
tobs = r*np.sqrt((n-2)/(1-pow(r,2)))
print(tobs)
p =2*(1-t.cdf(tobs,n-2))
print(p)

# code Python bài tập 1
import numpy as np
import pandas as pd
from scipy.stats import t
from scipy.stats import f
df = pd.read_csv("/content/drive/My Drive/Dataset/dataBT1_lecture9.csv")
x = df.values[:,0]
y = df.values[:,1]
n = len(x)
print(n)
m = len(y)
print(m)
xbar =np.mean(x)
print(xbar)
ybar =np.mean(y)
print(ybar)
s12 = np.var(x)
print(s12)
s22 = np.var(y)
print(s22)
Fobs = s12/s22
print(Fobs)
p1 = f.cdf(Fobs,n-1,m-1)+1-f.cdf(1/Fobs,n-1,m-1)
print(p1)
s2 =((n-1)*s12+(m-1)*s22)/(n+m-2)
print(s2)
tobs =(xbar - ybar)/np.sqrt(s2/n+s2/m)
print(tobs)
p2 =1-t.cdf(tobs,n+m-2)
print(p2)

# code python bài tập 2
from scipy.stats import mannwhitneyu
x=[7,5,6,4,12]
y=[3,6,4,2,1]
# compare samples
stat, p = mannwhitneyu(x, y)
print('Statistics=%.3f, p=%.3f' % (stat, p))
# interpret
alpha = 0.05
if p > alpha:
	print('Same distribution (fail to reject H0)')
else:
	print('Different distribution (reject H0)')

# code Python bài tập 3
import numpy as np
import pandas as pd
from scipy.stats import t
df = pd.read_csv("/content/drive/My Drive/Dataset/dataBT3_lecture9.csv",sep="\t")
x = df.values[:,1]
y = df.values[:,2]
n = len(x)
print(n)
xbar =np.mean(x)
print(xbar)
ybar =np.mean(y)
print(ybar)
xybar =np.mean(x*y)
print(xybar)
x2bar =np.mean(pow(x,2))
print(x2bar)
y2bar =np.mean(pow(y,2))
print(y2bar)
r =(xybar - xbar*ybar)/np.sqrt((x2bar - pow(xbar,2))*(y2bar - pow(ybar,2)))
print(r)
tobs = r*np.sqrt((n-2)/(1-pow(r,2)))
print(tobs)
p =1-t.cdf(tobs,n-2)
print(p)