# -*- coding: utf-8 -*-
"""Lecture8a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nosQ2PX26Qfdm7MKQpxmiEpFEKFmvOKv
"""

# ví dụ trong đặt vấn đề
import numpy as np
import pandas as pd
from scipy.stats import t
df = pd.read_csv("/content/drive/My Drive/Dataset/data1_lecture8.csv")
x = df.values[:,0]
n = len(x)
print(n)
xbar =np.mean(x)
print(xbar)
s = np.std(x)
print(s)
mu0 = 200
tobs =(xbar - mu0)/(s/np.sqrt(n))
print(tobs)
pvalue = 1- t.cdf(tobs,n-1)
print(pvalue)

# Ví dụ minh hoạ
import numpy as np
import pandas as pd
from scipy.stats import t
df = pd.read_csv("/content/drive/My Drive/Dataset/data2_lecture8.csv")
x = df.values[:,0]
n = len(x)
print(n)
xbar =np.mean(x)
print(xbar)
s = np.std(x)
print(s)
mu0 = 2
tobs =(xbar - mu0)/(s/np.sqrt(n))
print(tobs)
pvalue = 1- t.cdf(tobs,n-1)
print(pvalue)

# bài tập 1
import numpy as np
import pandas as pd
from scipy.stats import t
df = pd.read_csv("/content/drive/My Drive/Dataset/data3_lecture8.csv",sep = "\t")
x = df.values[:,0]
y = df.values[:,1]
n = len(x)
print(n)
m=len(y)
print(m)
xbar =np.mean(x)
print(xbar)
ybar =np.mean(y)
print(ybar)
s12 = np.var(x)
print(s12)
s22 = np.var(y)
print(s22)
s2 =((n-1)*s12+(m-1)*s22)/(n+m-2)
print(s2)
tobs =(xbar - ybar)/np.sqrt(s2*(1/n+1/m))
print(tobs)
pvalue = 2*(1- t.cdf(np.abs(tobs),n+m-2))
print(pvalue)

# bài tập 2
import numpy as np
import pandas as pd
from scipy.stats import norm
df = pd.read_csv("/content/drive/My Drive/Dataset/data4_lecture8.csv")
x = df.values[:,0]
n = len(x)
print(n)
xbar =np.mean(x)
print(xbar)
s = np.std(x)
print(s)
mu0 = 200
Zobs =(xbar - mu0)/(s/np.sqrt(n))
print(Zobs)
pvalue = norm.cdf(Zobs)
print(pvalue)